### ISSUE TITLE
Needs a README.md with link to getting started instructions

### ISSUE THREAD

**Issue by jelkner** [ahirschberg/code_steps#11] opened 2016-07-02 18:58 UTC
I just did a git clone of code_steps and installed ruby.  Now I'm not sure what to do to try it out.  I'd like to be able to do a git pull and see some kind of instructions as to the work flow to use to test it out.

**Comment by ahirschberg** [comment] 2016-07-03 20:54
Closing this as duplicate of #12

**Closed as completed by ahirschberg** 2016-07-03 20:54 UTC
Labels: duplicate
